---
- name: configuring firewall
  hosts: servers
  become: yes
  tasks:
    - name: Installing ufw
      apt:
        name: ufw
        state: present
      
    - name: Allow SSH
      ufw:
        rule: allow
        name: OpenSSH

    - name: Enable ufw
      ufw:
        state: enabled

  