name: 'terraform-automation'

on:
  push:
    branches:
      - terraform-automation
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "ap-south-1"
  
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0

      - name: set up terraform
        uses: hashicorp/setup-terraform@v2.0.0

      - name: Terraform init
        run : terraform init

      - name: Terraform plan
        run : terraform plan

      - name: Terraform apply
        if : github.ref == 'refs/heads/terraform-automation'
        run: terraform apply -auto-approve
